/** Generated by scripts/image-sizes.mjs — do not edit by hand.
 *  Intrinsic pixel dimensions of everything in public/images, so article
 *  images render at their real proportion with no layout shift. */
export const imageSizes: Record<string, [number, number]> = {
  "/images/anchoring-effect/01.png": [
    1288,
    1348
  ],
  "/images/anchoring-effect/02.png": [
    806,
    544
  ],
  "/images/baemin-address-setting/01.png": [
    466,
    1010
  ],
  "/images/baemin-address-setting/02.png": [
    466,
    1010
  ],
  "/images/baemin-address-setting/03.png": [
    466,
    1010
  ],
  "/images/baemin-address-setting/04.png": [
    466,
    1010
  ],
  "/images/baemin-address-setting/05.png": [
    466,
    1010
  ],
  "/images/baemin-address-setting/06.png": [
    466,
    1010
  ],
  "/images/baemin-address-setting/07.png": [
    466,
    1010
  ],
  "/images/baemin-address-setting/08.jpg": [
    800,
    947
  ],
  "/images/baemin-address-setting/09.png": [
    512,
    512
  ],
  "/images/bounce-rate-vs-exit-rate/01.png": [
    2000,
    2000
  ],
  "/images/bounce-rate-vs-exit-rate/02.jpg": [
    700,
    464
  ],
  "/images/bounce-rate-vs-exit-rate/03.png": [
    1280,
    882
  ],
  "/images/bounce-rate-vs-exit-rate/04.png": [
    800,
    533
  ],
  "/images/bounce-rate-vs-exit-rate/05.png": [
    652,
    382
  ],
  "/images/bounce-rate-vs-exit-rate/06.jpg": [
    870,
    418
  ],
  "/images/cashless-effect/01.png": [
    1000,
    1000
  ],
  "/images/cashless-effect/02.jpg": [
    700,
    476
  ],
  "/images/cashless-effect/03.jpg": [
    600,
    415
  ],
  "/images/cashless-effect/04.png": [
    800,
    445
  ],
  "/images/chunking/01.png": [
    1322,
    286
  ],
  "/images/chunking/02.png": [
    1484,
    226
  ],
  "/images/chunking/03.png": [
    1506,
    888
  ],
  "/images/chunking/04.png": [
    1269,
    1287
  ],
  "/images/chunking/05.png": [
    1440,
    737
  ],
  "/images/chunking/06.png": [
    1269,
    1437
  ],
  "/images/cocktail-party-effect/01.png": [
    100,
    67
  ],
  "/images/confirmation-bias/01.png": [
    1699,
    774
  ],
  "/images/confirmation-bias/02.jpg": [
    364,
    273
  ],
  "/images/confirmation-bias/03.webp": [
    420,
    410
  ],
  "/images/coupang-interface-intent/01.png": [
    1273,
    297
  ],
  "/images/coupang-interface-intent/02.png": [
    1267,
    702
  ],
  "/images/coupang-interface-intent/03.png": [
    1235,
    697
  ],
  "/images/coupang-interface-intent/04.png": [
    1238,
    693
  ],
  "/images/coupang-interface-intent/05.png": [
    1239,
    699
  ],
  "/images/coupang-interface-intent/06.png": [
    1236,
    695
  ],
  "/images/decision-fatigue/01.png": [
    100,
    74
  ],
  "/images/decision-fatigue/02.png": [
    100,
    49
  ],
  "/images/emotional-design-to-lifestyle-ux/01.png": [
    1584,
    1160
  ],
  "/images/emotional-design-to-lifestyle-ux/02.png": [
    1764,
    1160
  ],
  "/images/emotional-design-to-lifestyle-ux/03.png": [
    1582,
    1096
  ],
  "/images/emotional-design-to-lifestyle-ux/04.png": [
    1758,
    1098
  ],
  "/images/emotional-design-to-lifestyle-ux/05.jpg": [
    840,
    473
  ],
  "/images/emotional-design-to-lifestyle-ux/06.jpg": [
    840,
    540
  ],
  "/images/empathy-gap/01.png": [
    1024,
    880
  ],
  "/images/face-ism-effect/01.png": [
    100,
    67
  ],
  "/images/filter-bubble/01.png": [
    2000,
    2000
  ],
  "/images/filter-bubble/02.png": [
    800,
    440
  ],
  "/images/filter-bubble/03.png": [
    1280,
    621
  ],
  "/images/filter-bubble/04.png": [
    557,
    620
  ],
  "/images/fittss-law/01.png": [
    800,
    433
  ],
  "/images/fittss-law/02.png": [
    941,
    532
  ],
  "/images/fittss-law/03.png": [
    1732,
    786
  ],
  "/images/fittss-law/04.png": [
    1002,
    323
  ],
  "/images/fittss-law/05.png": [
    1400,
    693
  ],
  "/images/fittss-law/06.png": [
    1024,
    576
  ],
  "/images/fittss-law/07.png": [
    1141,
    463
  ],
  "/images/fittss-law/08.png": [
    1024,
    576
  ],
  "/images/framing-effect/01.png": [
    2000,
    2000
  ],
  "/images/framing-effect/02.png": [
    1284,
    989
  ],
  "/images/fresh-start-effect/02.png": [
    1072,
    978
  ],
  "/images/fundamental-attribution-error/01.png": [
    1000,
    1000
  ],
  "/images/fundamental-attribution-error/02.png": [
    549,
    216
  ],
  "/images/fundamental-attribution-error/03.jpg": [
    800,
    376
  ],
  "/images/fundamental-attribution-error/04.png": [
    1024,
    751
  ],
  "/images/gestalt-principles/01.png": [
    2000,
    2000
  ],
  "/images/gestalt-principles/02.jpg": [
    1174,
    582
  ],
  "/images/gestalt-principles/03.jpg": [
    645,
    304
  ],
  "/images/gestalt-principles/04.jpg": [
    1280,
    720
  ],
  "/images/gestalt-principles/05.png": [
    1024,
    320
  ],
  "/images/gestalt-principles/06.png": [
    1193,
    326
  ],
  "/images/gestalt-principles/07.gif": [
    500,
    580
  ],
  "/images/gestalt-principles/08.png": [
    495,
    309
  ],
  "/images/hicks-law/01.png": [
    1414,
    1074
  ],
  "/images/hicks-law/02.png": [
    1706,
    1092
  ],
  "/images/hicks-law/03.png": [
    1186,
    1272
  ],
  "/images/hicks-law/04.png": [
    728,
    1420
  ],
  "/images/hicks-law/05.png": [
    1756,
    886
  ],
  "/images/hicks-law/06.png": [
    1690,
    942
  ],
  "/images/holistic-vs-analytic-cognition/01.png": [
    1238,
    681
  ],
  "/images/holistic-vs-analytic-cognition/02.png": [
    1240,
    678
  ],
  "/images/holistic-vs-analytic-cognition/03.png": [
    1229,
    678
  ],
  "/images/holistic-vs-analytic-cognition/04.png": [
    1236,
    675
  ],
  "/images/holistic-vs-analytic-cognition/05.jpg": [
    300,
    169
  ],
  "/images/holistic-vs-analytic-cognition/06.jpg": [
    900,
    822
  ],
  "/images/holistic-vs-analytic-cognition/07.png": [
    1239,
    687
  ],
  "/images/holistic-vs-analytic-cognition/08.png": [
    850,
    433
  ],
  "/images/holistic-vs-analytic-cognition/09.webp": [
    1009,
    918
  ],
  "/images/holistic-vs-analytic-cognition/10.jpg": [
    2554,
    2025
  ],
  "/images/holistic-vs-analytic-cognition/11.png": [
    986,
    595
  ],
  "/images/holistic-vs-analytic-cognition/12.png": [
    1809,
    907
  ],
  "/images/holistic-vs-analytic-cognition/13.png": [
    300,
    635
  ],
  "/images/holistic-vs-analytic-cognition/14.jpg": [
    960,
    708
  ],
  "/images/holistic-vs-analytic-cognition/15.jpg": [
    622,
    1280
  ],
  "/images/if-design-trend-2026/01.png": [
    1513,
    848
  ],
  "/images/if-design-trend-2026/02.png": [
    885,
    564
  ],
  "/images/if-design-trend-2026/03.png": [
    514,
    677
  ],
  "/images/if-design-trend-2026/04.png": [
    729,
    626
  ],
  "/images/if-design-trend-2026/05.png": [
    625,
    472
  ],
  "/images/if-design-trend-2026/06.png": [
    622,
    563
  ],
  "/images/if-design-trend-2026/07.png": [
    1271,
    673
  ],
  "/images/if-design-trend-2026/08.png": [
    624,
    679
  ],
  "/images/if-design-trend-2026/09.png": [
    1270,
    677
  ],
  "/images/if-design-trend-2026/10.png": [
    1272,
    676
  ],
  "/images/if-design-trend-2026/11.png": [
    515,
    573
  ],
  "/images/ikea-effect/01.jpg": [
    1153,
    649
  ],
  "/images/ikea-effect/02.png": [
    435,
    461
  ],
  "/images/ikea-effect/03.jpg": [
    985,
    1011
  ],
  "/images/is-personalization-good-ux/01.jpg": [
    614,
    354
  ],
  "/images/is-personalization-good-ux/02.jpg": [
    547,
    365
  ],
  "/images/is-personalization-good-ux/03.png": [
    1078,
    638
  ],
  "/images/is-personalization-good-ux/04.jpg": [
    590,
    320
  ],
  "/images/is-personalization-good-ux/05.png": [
    571,
    502
  ],
  "/images/is-personalization-good-ux/06.png": [
    1003,
    604
  ],
  "/images/is-personalization-good-ux/07.png": [
    1280,
    720
  ],
  "/images/is-personalization-good-ux/08.jpg": [
    1167,
    700
  ],
  "/images/is-personalization-good-ux/09.png": [
    674,
    296
  ],
  "/images/is-personalization-good-ux/10.png": [
    696,
    280
  ],
  "/images/is-personalization-good-ux/11.png": [
    290,
    410
  ],
  "/images/is-personalization-good-ux/12.png": [
    509,
    463
  ],
  "/images/is-personalization-good-ux/13.jpg": [
    1280,
    488
  ],
  "/images/is-personalization-good-ux/14.png": [
    599,
    306
  ],
  "/images/is-personalization-good-ux/15.jpg": [
    357,
    560
  ],
  "/images/is-personalization-good-ux/16.jpg": [
    1280,
    727
  ],
  "/images/is-personalization-good-ux/17.jpg": [
    1280,
    995
  ],
  "/images/is-personalization-good-ux/18.jpg": [
    720,
    499
  ],
  "/images/is-personalization-good-ux/19.jpg": [
    720,
    1114
  ],
  "/images/jakobs-law/01.png": [
    727,
    610
  ],
  "/images/jakobs-law/02.png": [
    1442,
    400
  ],
  "/images/jakobs-law/03.png": [
    1474,
    914
  ],
  "/images/method-of-loci/01.jpg": [
    934,
    716
  ],
  "/images/method-of-loci/02.png": [
    700,
    434
  ],
  "/images/millers-law/01.png": [
    2000,
    2000
  ],
  "/images/millers-law/02.png": [
    1023,
    491
  ],
  "/images/millers-law/03.png": [
    1280,
    550
  ],
  "/images/millers-law/04.png": [
    960,
    540
  ],
  "/images/millers-law/05.png": [
    3430,
    2368
  ],
  "/images/naver-booking-access/01.png": [
    902,
    1214
  ],
  "/images/naver-booking-access/02.png": [
    902,
    1214
  ],
  "/images/naver-booking-access/03.png": [
    872,
    1232
  ],
  "/images/naver-booking-access/04.png": [
    1280,
    823
  ],
  "/images/naver-booking-access/05.png": [
    1280,
    729
  ],
  "/images/naver-booking-access/06.png": [
    882,
    1596
  ],
  "/images/naver-booking-access/07.png": [
    882,
    1596
  ],
  "/images/naver-booking-access/08.png": [
    876,
    1608
  ],
  "/images/naver-booking-access/09.jpg": [
    161,
    161
  ],
  "/images/normans-seven-stages-of-action/01.png": [
    1000,
    1000
  ],
  "/images/normans-seven-stages-of-action/02.png": [
    800,
    383
  ],
  "/images/novelty-effect/01.jpg": [
    1400,
    933
  ],
  "/images/peak-end-rule/01.png": [
    2000,
    2000
  ],
  "/images/peak-end-rule/02.png": [
    605,
    404
  ],
  "/images/peak-end-rule/03.jpg": [
    860,
    400
  ],
  "/images/peak-end-rule/04.jpg": [
    1200,
    800
  ],
  "/images/peak-end-rule/05.jpg": [
    720,
    500
  ],
  "/images/poka-yoke/01.png": [
    1000,
    1000
  ],
  "/images/poka-yoke/02.gif": [
    508,
    514
  ],
  "/images/poka-yoke/03.png": [
    1106,
    1654
  ],
  "/images/poka-yoke/04.jpg": [
    482,
    242
  ],
  "/images/poka-yoke/05.png": [
    456,
    278
  ],
  "/images/poka-yoke/06.png": [
    944,
    441
  ],
  "/images/poka-yoke/07.png": [
    945,
    442
  ],
  "/images/poka-yoke/08.png": [
    1218,
    603
  ],
  "/images/poka-yoke/09.png": [
    1280,
    1040
  ],
  "/images/postels-law/01.png": [
    100,
    48
  ],
  "/images/postels-law/02.png": [
    100,
    49
  ],
  "/images/postels-law/03.png": [
    100,
    56
  ],
  "/images/postels-law/04.png": [
    3338,
    1687
  ],
  "/images/postels-law/05.png": [
    3338,
    1501
  ],
  "/images/primacy-effect/01.png": [
    100,
    62
  ],
  "/images/primacy-effect/02.png": [
    100,
    54
  ],
  "/images/primacy-effect/03.png": [
    100,
    47
  ],
  "/images/primacy-effect/04.png": [
    100,
    56
  ],
  "/images/principle-of-pragnanz/01.png": [
    2000,
    2000
  ],
  "/images/principle-of-pragnanz/02.png": [
    700,
    394
  ],
  "/images/principle-of-pragnanz/03.png": [
    700,
    394
  ],
  "/images/principle-of-pragnanz/04.jpg": [
    900,
    600
  ],
  "/images/principle-of-pragnanz/05.jpg": [
    960,
    500
  ],
  "/images/principle-of-pragnanz/06.jpg": [
    1280,
    942
  ],
  "/images/progressive-disclosure/01.png": [
    1500,
    760
  ],
  "/images/progressive-disclosure/02.png": [
    1500,
    1000
  ],
  "/images/progressive-disclosure/03.png": [
    1500,
    1000
  ],
  "/images/progressive-disclosure/04.png": [
    1500,
    650
  ],
  "/images/progressive-disclosure/05.png": [
    1500,
    1000
  ],
  "/images/prototyping/01.png": [
    2000,
    2000
  ],
  "/images/prototyping/02.png": [
    1075,
    633
  ],
  "/images/prototyping/03.png": [
    1069,
    656
  ],
  "/images/prototyping/04.jpg": [
    560,
    220
  ],
  "/images/prototyping/05.png": [
    584,
    330
  ],
  "/images/prototyping/06.jpg": [
    1280,
    853
  ],
  "/images/prototyping/07.jpg": [
    1280,
    879
  ],
  "/images/prototyping/08.png": [
    1066,
    583
  ],
  "/images/provide-exit-points/01.png": [
    1456,
    372
  ],
  "/images/reactance-effect/01.jpg": [
    960,
    540
  ],
  "/images/reactance-effect/02.png": [
    1418,
    960
  ],
  "/images/reactance-effect/03.png": [
    1920,
    1053
  ],
  "/images/recognition-over-recall/01.png": [
    1256,
    1044
  ],
  "/images/recognition-over-recall/02.png": [
    900,
    704
  ],
  "/images/recognition-over-recall/03.png": [
    847,
    541
  ],
  "/images/recognition-over-recall/04.png": [
    1099,
    723
  ],
  "/images/recognition-over-recall/05.jpg": [
    1600,
    900
  ],
  "/images/recognition-over-recall/06.png": [
    1177,
    672
  ],
  "/images/recognition-over-recall/07.png": [
    1248,
    702
  ],
  "/images/social-proof/01.png": [
    1000,
    1000
  ],
  "/images/social-proof/02.png": [
    821,
    635
  ],
  "/images/social-proof/03.jpg": [
    1280,
    720
  ],
  "/images/streisand-effect/01.png": [
    1000,
    1000
  ],
  "/images/streisand-effect/02.jpg": [
    1280,
    720
  ],
  "/images/streisand-effect/03.png": [
    601,
    591
  ],
  "/images/streisand-effect/04.png": [
    768,
    741
  ],
  "/images/streisand-effect/05.jpg": [
    640,
    418
  ],
  "/images/temptation-bundling/01.png": [
    1000,
    1000
  ],
  "/images/temptation-bundling/02.png": [
    994,
    567
  ],
  "/images/temptation-bundling/03.jpg": [
    1200,
    630
  ],
  "/images/temptation-bundling/04.jpg": [
    1100,
    706
  ],
  "/images/temptation-bundling/05.png": [
    1012,
    445
  ],
  "/images/user-research/01.png": [
    2000,
    2000
  ],
  "/images/user-research/02.png": [
    799,
    493
  ],
  "/images/user-research/03.png": [
    500,
    400
  ],
  "/images/user-research/04.png": [
    450,
    697
  ],
  "/images/user-scanning/01.png": [
    2000,
    2000
  ],
  "/images/user-scanning/02.png": [
    990,
    560
  ],
  "/images/user-scanning/03.jpg": [
    785,
    392
  ],
  "/images/user-scanning/04.png": [
    595,
    408
  ],
  "/images/von-restorff-effect/01.png": [
    913,
    407
  ],
  "/images/von-restorff-effect/02.png": [
    1070,
    656
  ],
  "/images/von-restorff-effect/03.jpg": [
    685,
    839
  ],
  "/images/von-restorff-effect/04.png": [
    1888,
    907
  ],
  "/images/von-restorff-effect/05.png": [
    640,
    192
  ],
  "/images/von-restorff-effect/06.png": [
    1024,
    576
  ],
  "/images/von-restorff-effect/07.png": [
    402,
    864
  ],
  "/images/von-restorff-effect/08.gif": [
    480,
    360
  ],
  "/images/von-restorff-effect/09.png": [
    589,
    909
  ],
  "/images/von-restorff-effect/10.png": [
    1305,
    915
  ],
  "/images/xr-ux-and-ai-glass/01.jpg": [
    640,
    483
  ],
  "/images/xr-ux-and-ai-glass/02.png": [
    1426,
    794
  ],
  "/images/xr-ux-and-ai-glass/03.png": [
    1429,
    801
  ],
  "/images/xr-ux-and-ai-glass/04.png": [
    2240,
    1260
  ],
  "/images/xr-ux-and-ai-glass/05.png": [
    934,
    522
  ],
  "/images/xr-ux-and-ai-glass/06.png": [
    932,
    526
  ],
  "/images/xr-ux-and-ai-glass/07.png": [
    931,
    524
  ],
  "/images/xr-ux-and-ai-glass/08.jpg": [
    3000,
    1688
  ],
  "/images/xr-ux-and-ai-glass/09.jpg": [
    1200,
    900
  ],
  "/images/xr-ux-and-ai-glass/10.jpg": [
    640,
    341
  ],
  "/images/xr-ux-and-ai-glass/11.png": [
    933,
    522
  ],
  "/images/zeigarnik-effect/01.png": [
    552,
    391
  ],
  "/images/zeigarnik-effect/02.png": [
    195,
    392
  ],
  "/images/zeigarnik-effect/03.png": [
    197,
    391
  ],
  "/images/zeigarnik-effect/04.png": [
    632,
    485
  ],
  "/images/zeigarnik-effect/05.png": [
    761,
    489
  ],
  "/images/zeigarnik-effect/06.png": [
    215,
    489
  ],
  "/images/zeigarnik-effect/07.png": [
    650,
    490
  ]
};

export function imageSize(src: string): [number, number] | null {
  return imageSizes[src] ?? null;
}

export function imageRatio(src: string): number | null {
  const s = imageSizes[src];
  return s ? s[0] / s[1] : null;
}
