/** Generated by scripts/image-sizes.mjs — do not edit by hand.
 *  Intrinsic pixel dimensions of everything in public/images, so article
 *  images render at their real proportion with no layout shift. */
export const imageSizes: Record<string, [number, number]> = {
  "/images/anchoring-effect/01.png": [
    1288,
    1348
  ],
  "/images/anchoring-effect/02.png": [
    806,
    544
  ],
  "/images/bounce-rate-vs-exit-rate/01.png": [
    2000,
    2000
  ],
  "/images/bounce-rate-vs-exit-rate/02.jpg": [
    700,
    464
  ],
  "/images/bounce-rate-vs-exit-rate/03.png": [
    1280,
    882
  ],
  "/images/bounce-rate-vs-exit-rate/04.png": [
    800,
    533
  ],
  "/images/bounce-rate-vs-exit-rate/05.png": [
    652,
    382
  ],
  "/images/bounce-rate-vs-exit-rate/06.jpg": [
    870,
    418
  ],
  "/images/cashless-effect/01.png": [
    1000,
    1000
  ],
  "/images/cashless-effect/02.jpg": [
    700,
    476
  ],
  "/images/cashless-effect/03.jpg": [
    600,
    415
  ],
  "/images/cashless-effect/04.png": [
    800,
    445
  ],
  "/images/chunking/01.png": [
    1322,
    286
  ],
  "/images/chunking/02.png": [
    1484,
    226
  ],
  "/images/chunking/03.png": [
    1506,
    888
  ],
  "/images/chunking/04.png": [
    1269,
    1287
  ],
  "/images/chunking/05.png": [
    1440,
    737
  ],
  "/images/chunking/06.png": [
    1269,
    1437
  ],
  "/images/confirmation-bias/01.png": [
    1699,
    774
  ],
  "/images/confirmation-bias/02.jpg": [
    364,
    273
  ],
  "/images/confirmation-bias/03.webp": [
    420,
    410
  ],
  "/images/empathy-gap/01.png": [
    1024,
    880
  ],
  "/images/filter-bubble/01.png": [
    2000,
    2000
  ],
  "/images/filter-bubble/02.png": [
    800,
    440
  ],
  "/images/filter-bubble/03.png": [
    1280,
    621
  ],
  "/images/filter-bubble/04.png": [
    557,
    620
  ],
  "/images/fittss-law/01.png": [
    800,
    433
  ],
  "/images/fittss-law/02.png": [
    941,
    532
  ],
  "/images/fittss-law/03.png": [
    1732,
    786
  ],
  "/images/fittss-law/04.png": [
    1002,
    323
  ],
  "/images/fittss-law/05.png": [
    1400,
    693
  ],
  "/images/fittss-law/06.png": [
    1024,
    576
  ],
  "/images/fittss-law/07.png": [
    1141,
    463
  ],
  "/images/fittss-law/08.png": [
    1024,
    576
  ],
  "/images/framing-effect/01.png": [
    2000,
    2000
  ],
  "/images/framing-effect/02.png": [
    1284,
    989
  ],
  "/images/fundamental-attribution-error/01.png": [
    1000,
    1000
  ],
  "/images/fundamental-attribution-error/02.png": [
    549,
    216
  ],
  "/images/fundamental-attribution-error/03.jpg": [
    800,
    376
  ],
  "/images/fundamental-attribution-error/04.png": [
    1024,
    751
  ],
  "/images/gestalt-principles/01.png": [
    2000,
    2000
  ],
  "/images/gestalt-principles/02.jpg": [
    1174,
    582
  ],
  "/images/gestalt-principles/03.jpg": [
    645,
    304
  ],
  "/images/gestalt-principles/04.jpg": [
    1280,
    720
  ],
  "/images/gestalt-principles/05.png": [
    1024,
    320
  ],
  "/images/gestalt-principles/06.png": [
    1193,
    326
  ],
  "/images/gestalt-principles/07.gif": [
    500,
    580
  ],
  "/images/gestalt-principles/08.png": [
    495,
    309
  ],
  "/images/hicks-law/01.png": [
    1414,
    1074
  ],
  "/images/hicks-law/02.png": [
    1706,
    1092
  ],
  "/images/hicks-law/03.png": [
    1186,
    1272
  ],
  "/images/hicks-law/04.png": [
    728,
    1420
  ],
  "/images/hicks-law/05.png": [
    1756,
    886
  ],
  "/images/hicks-law/06.png": [
    1690,
    942
  ],
  "/images/holistic-vs-analytic-cognition/01.png": [
    1238,
    681
  ],
  "/images/holistic-vs-analytic-cognition/02.png": [
    1240,
    678
  ],
  "/images/holistic-vs-analytic-cognition/03.png": [
    1229,
    678
  ],
  "/images/holistic-vs-analytic-cognition/04.png": [
    1236,
    675
  ],
  "/images/holistic-vs-analytic-cognition/05.jpg": [
    300,
    169
  ],
  "/images/holistic-vs-analytic-cognition/06.jpg": [
    900,
    822
  ],
  "/images/holistic-vs-analytic-cognition/07.png": [
    1239,
    687
  ],
  "/images/holistic-vs-analytic-cognition/08.png": [
    850,
    433
  ],
  "/images/holistic-vs-analytic-cognition/09.webp": [
    1009,
    918
  ],
  "/images/holistic-vs-analytic-cognition/10.jpg": [
    2554,
    2025
  ],
  "/images/holistic-vs-analytic-cognition/11.png": [
    986,
    595
  ],
  "/images/holistic-vs-analytic-cognition/12.png": [
    1809,
    907
  ],
  "/images/holistic-vs-analytic-cognition/13.png": [
    300,
    635
  ],
  "/images/holistic-vs-analytic-cognition/14.jpg": [
    960,
    708
  ],
  "/images/holistic-vs-analytic-cognition/15.jpg": [
    622,
    1280
  ],
  "/images/ikea-effect/01.jpg": [
    1153,
    649
  ],
  "/images/ikea-effect/02.png": [
    435,
    461
  ],
  "/images/ikea-effect/03.jpg": [
    985,
    1011
  ],
  "/images/jakobs-law/01.png": [
    727,
    610
  ],
  "/images/jakobs-law/02.png": [
    1442,
    400
  ],
  "/images/jakobs-law/03.png": [
    1474,
    914
  ],
  "/images/millers-law/01.png": [
    2000,
    2000
  ],
  "/images/millers-law/02.png": [
    1023,
    491
  ],
  "/images/millers-law/03.png": [
    1280,
    550
  ],
  "/images/millers-law/04.png": [
    960,
    540
  ],
  "/images/millers-law/05.png": [
    3430,
    2368
  ],
  "/images/normans-seven-stages-of-action/01.png": [
    1000,
    1000
  ],
  "/images/normans-seven-stages-of-action/02.png": [
    800,
    383
  ],
  "/images/poka-yoke/01.png": [
    1000,
    1000
  ],
  "/images/poka-yoke/02.gif": [
    508,
    514
  ],
  "/images/poka-yoke/03.png": [
    1106,
    1654
  ],
  "/images/poka-yoke/04.jpg": [
    482,
    242
  ],
  "/images/poka-yoke/05.png": [
    456,
    278
  ],
  "/images/poka-yoke/06.png": [
    944,
    441
  ],
  "/images/poka-yoke/07.png": [
    945,
    442
  ],
  "/images/poka-yoke/08.png": [
    1218,
    603
  ],
  "/images/poka-yoke/09.png": [
    1280,
    1040
  ],
  "/images/principle-of-pragnanz/01.png": [
    2000,
    2000
  ],
  "/images/principle-of-pragnanz/02.png": [
    700,
    394
  ],
  "/images/principle-of-pragnanz/03.png": [
    700,
    394
  ],
  "/images/principle-of-pragnanz/04.jpg": [
    900,
    600
  ],
  "/images/principle-of-pragnanz/05.jpg": [
    960,
    500
  ],
  "/images/principle-of-pragnanz/06.jpg": [
    1280,
    942
  ],
  "/images/progressive-disclosure/01.png": [
    1500,
    760
  ],
  "/images/progressive-disclosure/02.png": [
    1500,
    1000
  ],
  "/images/progressive-disclosure/03.png": [
    1500,
    1000
  ],
  "/images/progressive-disclosure/04.png": [
    1500,
    650
  ],
  "/images/progressive-disclosure/05.png": [
    1500,
    1000
  ],
  "/images/prototyping/01.png": [
    2000,
    2000
  ],
  "/images/prototyping/02.png": [
    1075,
    633
  ],
  "/images/prototyping/03.png": [
    1069,
    656
  ],
  "/images/prototyping/04.jpg": [
    560,
    220
  ],
  "/images/prototyping/05.png": [
    584,
    330
  ],
  "/images/prototyping/06.jpg": [
    1280,
    853
  ],
  "/images/prototyping/07.jpg": [
    1280,
    879
  ],
  "/images/prototyping/08.png": [
    1066,
    583
  ],
  "/images/provide-exit-points/01.png": [
    1456,
    372
  ],
  "/images/social-proof/01.png": [
    1000,
    1000
  ],
  "/images/social-proof/02.png": [
    821,
    635
  ],
  "/images/social-proof/03.jpg": [
    1280,
    720
  ],
  "/images/streisand-effect/01.png": [
    1000,
    1000
  ],
  "/images/streisand-effect/02.jpg": [
    1280,
    720
  ],
  "/images/streisand-effect/03.png": [
    601,
    591
  ],
  "/images/streisand-effect/04.png": [
    768,
    741
  ],
  "/images/streisand-effect/05.jpg": [
    640,
    418
  ],
  "/images/temptation-bundling/01.png": [
    1000,
    1000
  ],
  "/images/temptation-bundling/02.png": [
    994,
    567
  ],
  "/images/temptation-bundling/03.jpg": [
    1200,
    630
  ],
  "/images/temptation-bundling/04.jpg": [
    1100,
    706
  ],
  "/images/temptation-bundling/05.png": [
    1012,
    445
  ],
  "/images/user-research/01.png": [
    2000,
    2000
  ],
  "/images/user-research/02.png": [
    799,
    493
  ],
  "/images/user-research/03.png": [
    500,
    400
  ],
  "/images/user-research/04.png": [
    450,
    697
  ],
  "/images/user-scanning/01.png": [
    2000,
    2000
  ],
  "/images/user-scanning/02.png": [
    990,
    560
  ],
  "/images/user-scanning/03.jpg": [
    785,
    392
  ],
  "/images/user-scanning/04.png": [
    595,
    408
  ],
  "/images/von-restorff-effect/01.png": [
    913,
    407
  ],
  "/images/von-restorff-effect/02.png": [
    1070,
    656
  ],
  "/images/von-restorff-effect/03.jpg": [
    685,
    839
  ],
  "/images/von-restorff-effect/04.png": [
    1888,
    907
  ],
  "/images/von-restorff-effect/05.png": [
    640,
    192
  ],
  "/images/von-restorff-effect/06.png": [
    1024,
    576
  ],
  "/images/von-restorff-effect/07.png": [
    402,
    864
  ],
  "/images/von-restorff-effect/08.gif": [
    480,
    360
  ],
  "/images/von-restorff-effect/09.png": [
    589,
    909
  ],
  "/images/von-restorff-effect/10.png": [
    1305,
    915
  ],
  "/images/xr-ux-and-ai-glass/01.jpg": [
    640,
    483
  ],
  "/images/xr-ux-and-ai-glass/02.png": [
    1426,
    794
  ],
  "/images/xr-ux-and-ai-glass/03.png": [
    1429,
    801
  ],
  "/images/xr-ux-and-ai-glass/04.png": [
    2240,
    1260
  ],
  "/images/xr-ux-and-ai-glass/05.png": [
    934,
    522
  ],
  "/images/xr-ux-and-ai-glass/06.png": [
    932,
    526
  ],
  "/images/xr-ux-and-ai-glass/07.png": [
    931,
    524
  ],
  "/images/xr-ux-and-ai-glass/08.jpg": [
    3000,
    1688
  ],
  "/images/xr-ux-and-ai-glass/09.jpg": [
    1200,
    900
  ],
  "/images/xr-ux-and-ai-glass/10.jpg": [
    640,
    341
  ],
  "/images/xr-ux-and-ai-glass/11.png": [
    933,
    522
  ],
  "/images/zeigarnik-effect/01.png": [
    552,
    391
  ],
  "/images/zeigarnik-effect/02.png": [
    195,
    392
  ],
  "/images/zeigarnik-effect/03.png": [
    197,
    391
  ],
  "/images/zeigarnik-effect/04.png": [
    632,
    485
  ],
  "/images/zeigarnik-effect/05.png": [
    761,
    489
  ],
  "/images/zeigarnik-effect/06.png": [
    215,
    489
  ],
  "/images/zeigarnik-effect/07.png": [
    650,
    490
  ]
};

export function imageSize(src: string): [number, number] | null {
  return imageSizes[src] ?? null;
}

export function imageRatio(src: string): number | null {
  const s = imageSizes[src];
  return s ? s[0] / s[1] : null;
}
