/**
 * Scans public/images and writes lib/data/image-sizes.ts — a map of
 * public path → [width, height]. The article renderer uses it to show every
 * image at its real proportion instead of forcing a crop.
 *
 *   node scripts/image-sizes.mjs
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = "public/images";

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

function png(b) {
  if (b.subarray(0, 8).toString("hex") !== "89504e470d0a1a0a") return null;
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
}

function gif(b) {
  if (b.subarray(0, 3).toString() !== "GIF") return null;
  return [b.readUInt16LE(6), b.readUInt16LE(8)];
}

function jpg(b) {
  if (b.readUInt16BE(0) !== 0xffd8) return null;
  let i = 2;
  while (i < b.length - 9) {
    if (b[i] !== 0xff) {
      i += 1;
      continue;
    }
    const marker = b[i + 1];
    if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
      return [b.readUInt16BE(i + 7), b.readUInt16BE(i + 5)];
    }
    i += 2 + b.readUInt16BE(i + 2);
  }
  return null;
}

function webp(b) {
  if (b.subarray(0, 4).toString() !== "RIFF" || b.subarray(8, 12).toString() !== "WEBP") {
    return null;
  }
  const fmt = b.subarray(12, 16).toString();
  if (fmt === "VP8X") return [1 + b.readUIntLE(24, 3), 1 + b.readUIntLE(27, 3)];
  if (fmt === "VP8 ") return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff];
  if (fmt === "VP8L") {
    const n = b.readUInt32LE(21);
    return [1 + (n & 0x3fff), 1 + ((n >> 14) & 0x3fff)];
  }
  return null;
}

const READERS = { ".png": png, ".jpg": jpg, ".jpeg": jpg, ".gif": gif, ".webp": webp };

const sizes = {};
const failed = [];

for (const file of walk(ROOT).sort()) {
  const ext = file.slice(file.lastIndexOf(".")).toLowerCase();
  const read = READERS[ext];
  if (!read) continue;
  const dims = read(readFileSync(file));
  if (dims && dims[0] > 0 && dims[1] > 0) sizes["/" + file.replace(/^public\//, "")] = dims;
  else failed.push(file);
}

const body = `/** Generated by scripts/image-sizes.mjs — do not edit by hand.
 *  Intrinsic pixel dimensions of everything in public/images, so article
 *  images render at their real proportion with no layout shift. */
export const imageSizes: Record<string, [number, number]> = ${JSON.stringify(sizes, null, 2)};

export function imageSize(src: string): [number, number] | null {
  return imageSizes[src] ?? null;
}

export function imageRatio(src: string): number | null {
  const s = imageSizes[src];
  return s ? s[0] / s[1] : null;
}
`;

writeFileSync("lib/data/image-sizes.ts", body);
console.log(`✓ ${Object.keys(sizes).length} images measured`);
if (failed.length) console.warn(`! unreadable: ${failed.join(", ")}`);
